### ISSUE TITLE
Invalid tax value, 8

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposDaisy#2]
Реталикс не воспринимает эту ошибку как ошибку и у себя закрывает транзакцию как успешно оплаченную. Это вопрос к АСУ или нет?

[27.08.2024 17:26:28.934 ] [00047420] [ERROR] OPOS_E_FAILURE, 0, "Invalid tax value, 8"
[27.08.2024 17:26:28.934 ] [00047420] [DEBUG] ToleFiscalPrinter.EndFiscalReceipt(False)=111

[Uploading SHTRIH-M-OPOS-1_2024.08.27.log…]()

**Comment by VitalyKravtsov2016** [comment]
Если EndFiscalReceipt вернул ошибку, что либо чек не закрыт, либо неизвестно закрыт он или нет.
Лог почему-то не загрузился.

**Comment by Dafafgh** [comment]
[SHTRIH-M-OPOS-1_2024.08.27.log](https://github.com/user-attachments/files/16764526/SHTRIH-M-OPOS-1_2024.08.27.log)

обычно АСУ реагирует на данную ошибку отказом закрытия транзакции, в в этом случае почему то принял как успешную
