### ISSUE TITLE
FPTR_GD_GRAND_TOTAL

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposDaisy#3]
Вопрос по запросу наличных. В протоколе вроде есть команда получения счетчика наличных в кассе. Сейчас на запрос от реталикса приходит пустое значение. 
Запрос нужно добавить в драйвер или причина в другом?

[09.09.2024 13:10:06.572 ] [00005988] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '')
[09.09.2024 13:10:06.572 ] [00005988] [ERROR] OPOS_E_ILLEGAL, 0, "Invalid parameter value, DataItem='8'"
[09.09.2024 13:10:06.572 ] [00005988] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '')=106

[SHTRIH-M-OPOS-1_2024.09.09.log](https://github.com/user-attachments/files/16929166/SHTRIH-M-OPOS-1_2024.09.09.log)

**Comment by VitalyKravtsov2016** [comment]
Про какую команду речь?

**Comment by Dafafgh** [comment]
да без понятия
реталикс выдает ошибку

13:10:06.576  27........  Info......  TReturnsPrePay......  CheckFiscalCashBalan  NOT ENOUGH CASH IN THE FP: InDrawer = 2230.04; VoidAmount = 10.04; InFP = -0.01
13:10:06.577  27........  Info......  TReturnsPrePay......  DoSingleDoubleFlow..  Failed on CheckSingleDoubleRecieptType. ResultCode=627

в логах только один запрос к OPOS в это время

13:10:06.573  ..........  Info......  TFPWebKassa.........  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=106, sGrandSales=

[POSITIVE32-20240909.log](https://github.com/user-attachments/files/16929555/POSITIVE32-20240909.log)

[STOREPOINTIO-20240909.log](https://github.com/user-attachments/files/16929556/STOREPOINTIO-20240909.log)

**Comment by Dafafgh** [comment]
сработало
14:35:02.893  ..........  Info......  TFPWebKassa.........  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=0, sGrandSales=223004
